on:
    push:
      branches: [ "main" ]
      paths:
        - 'server/**'
        - '.github/workflows/azure-webapps-node.yml'
    workflow_dispatch:
  
env:
    AZURE_WEBAPP_NAME: app-gw-test-github     # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: './server'     # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '18.x'                      # set this to the node version to use
  
permissions:
    contents: read
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: "server"
      - name: npm install
        working-directory: ./server
        run: |
          npm install
          npm run build --if-present
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_CLIENT_ID: ${{ vars.VITE_CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          directory: ./server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: "./server"
  
    deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: "./server"
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}